version: '3'

services:

  db-madev:
    image: mysql:latest
    ports:
      - "9999:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

      MYSQL_DATABASE: $MOODLE_DATABASE_NAME
      MYSQL_USER: $MOODLE_DATABASE_USER
      MYSQL_PASSWORD: $MOODLE_DATABASE_PASSWORD

    volumes:
      - ./moodle-database.sql:/docker-entrypoint-initdb.d/datadump.sql

  moodle:
    image: ma-moodle-test
    build: .
    env_file:
      - .env
    ports:
      - "9980:80"
      - '9443:443'
    depends_on:
      - db-madev
